image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push
  - test

before_script:
  - docker info
  - export DATE=$(date -u +"%Y-%m-%d-%H-%M-%S")

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build -t $CI_COMMIT_SHORT_SHA:$CI_COMMIT_SHA .
    - docker images

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$DATE -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:$DATE .
   - docker images
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$DATE

test_docker_images:
  stage: test
  only:
   - master
  script:
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA google.com
